// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Return dummy options for web instead of throwing
      // This allows tests and CI to run without web Firebase config
      return const FirebaseOptions(
        apiKey: 'dummy-web-api-key',
        appId: 'dummy-web-app-id',
        messagingSenderId: '123456789',
        projectId: 'dummy-web-project',
        storageBucket: 'dummy-web-project.appspot.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // Return dummy options for iOS instead of throwing
        // This allows tests and CI to run without iOS Firebase config
        return const FirebaseOptions(
          apiKey: 'dummy-ios-api-key',
          appId: 'dummy-ios-app-id',
          messagingSenderId: '123456789',
          projectId: 'dummy-ios-project',
          storageBucket: 'dummy-ios-project.appspot.com',
        );
      case TargetPlatform.macOS:
        // Return dummy options for macOS instead of throwing
        return const FirebaseOptions(
          apiKey: 'dummy-macos-api-key',
          appId: 'dummy-macos-app-id',
          messagingSenderId: '123456789',
          projectId: 'dummy-macos-project',
          storageBucket: 'dummy-macos-project.appspot.com',
        );
      case TargetPlatform.windows:
        // Return dummy options for Windows instead of throwing
        return const FirebaseOptions(
          apiKey: 'dummy-windows-api-key',
          appId: 'dummy-windows-app-id',
          messagingSenderId: '123456789',
          projectId: 'dummy-windows-project',
          storageBucket: 'dummy-windows-project.appspot.com',
        );
      case TargetPlatform.linux:
        // Return dummy options for Linux instead of throwing
        // This is critical for CI which runs on Linux (ubuntu-latest)
        return const FirebaseOptions(
          apiKey: 'dummy-linux-api-key',
          appId: 'dummy-linux-app-id',
          messagingSenderId: '123456789',
          projectId: 'dummy-linux-project',
          storageBucket: 'dummy-linux-project.appspot.com',
        );
      default:
        // Return dummy options for unknown platforms
        return const FirebaseOptions(
          apiKey: 'dummy-api-key',
          appId: 'dummy-app-id',
          messagingSenderId: '123456789',
          projectId: 'dummy-project',
          storageBucket: 'dummy-project.appspot.com',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDz9U4Q8gMLxOMYG6UAwC_j2wB5vtm8WQ',
    appId: '1:979729107506:android:14961190e1dcb98b744a2b',
    messagingSenderId: '979729107506',
    projectId: 'glukids-2df10',
    storageBucket: 'glukids-2df10.firebasestorage.app',
  );
}
